"""add extras jsonb to community + calls + chat_sessions

Revision ID: 24cb77399481
Revises: 65a2d99d980d
Create Date: 2026-04-24 00:58:27.686689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24cb77399481'
down_revision: Union[str, Sequence[str], None] = '65a2d99d980d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_profiles', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('calls', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('chat_sessions', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('community_posts', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('community_replies', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_foreign_key('fk_companies_owner_id_users', 'companies', 'users', ['owner_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('user_gamification', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_gamification', 'extras')
    op.drop_constraint('fk_companies_owner_id_users', 'companies', type_='foreignkey')
    op.drop_column('community_replies', 'extras')
    op.drop_column('community_posts', 'extras')
    op.drop_column('chat_sessions', 'extras')
    op.drop_column('calls', 'extras')
    op.drop_column('anonymous_profiles', 'extras')
    # ### end Alembic commands ###
