"""add usage_logs audit_logs company_credits gamification_events + users.last_active_at

Revision ID: 3871cf2d1668
Revises: 24cb77399481
Create Date: 2026-04-30 17:16:19.552776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3871cf2d1668'
down_revision: Union[str, Sequence[str], None] = '24cb77399481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_uid', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_uid', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), server_default='user', nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_uid', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_company_created', 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.create_table('company_credits',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('plan_tier', sa.String(), server_default='free', nullable=False),
    sa.Column('credit_limit_usd', sa.Numeric(precision=12, scale=4), server_default='10', nullable=False),
    sa.Column('credits_consumed_mtd', sa.Numeric(precision=14, scale=8), server_default='0', nullable=False),
    sa.Column('credits_remaining', sa.Numeric(precision=14, scale=8), server_default='10', nullable=False),
    sa.Column('warning_threshold_pct', sa.Float(), server_default='80', nullable=False),
    sa.Column('alert_status', sa.String(), server_default='normal', nullable=False),
    sa.Column('total_lifetime_spend_usd', sa.Numeric(precision=14, scale=8), server_default='0', nullable=False),
    sa.Column('last_reset_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_warning_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_critical_sent_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=14, scale=8), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_logs_company_created', 'usage_logs', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_usage_logs_feature_created', 'usage_logs', ['feature', 'created_at'], unique=False)
    op.create_index('ix_usage_logs_user_created', 'usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('gamification_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gamification_events_company_created', 'gamification_events', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_gamification_events_user_created', 'gamification_events', ['user_id', 'created_at'], unique=False)
    # NOTE: calls.{caller,callee}_id, companies.owner_id, users.manager_id FKs
    # were intentionally dropped during Phase 6 ETL to handle cross-collection
    # insert-order issues. They remain dropped going forward — referential
    # integrity for those columns is enforced at the app layer.
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_index('ix_gamification_events_user_created', table_name='gamification_events')
    op.drop_index('ix_gamification_events_company_created', table_name='gamification_events')
    op.drop_table('gamification_events')
    op.drop_index('ix_usage_logs_user_created', table_name='usage_logs')
    op.drop_index('ix_usage_logs_feature_created', table_name='usage_logs')
    op.drop_index('ix_usage_logs_company_created', table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_table('company_credits')
    op.drop_index('ix_audit_logs_company_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
